name: ramp-template-kit
channels:
  - defaults
  - conda-forge
dependencies:
  - joblib
  - matplotlib
  - numpy
  - pandas
  - scikit-learn>=1.4
  - pip
  - pip:
    - ramp-workflow
    - -r requirements.txt
